import { Growcery } from '../models/growcery';

export const mockGrowceryList: Growcery[] = [
    {
      name: 'oasis juice',
      brand: 'Oasis',
      sale: 2.99,
      bulk: 1,
      error: false,
      regular: 3.99,
      grocer: 't&t',
      city: 'toronto',
      weight: 1.65,
      unit: 'L',
      upc: 5,
      vegan: true,
      packaged: true,
      expiry: 1231231212312,
    }, {
      name: 'panda oyster sauce',
      brand: 'Panda',
      sale: 4.5,
      bulk: 2,
      error: false,
      regular: 3.29,
      grocer: 't&t',
      city: 'toronto',
      weight: 510,
      unit: 'ml',
      upc: 5,
      vegan: false,
      packaged: true,
      expiry: 1231231212312,
    }, {
      name: 'kung fu soy sauce',
      brand: 'Kung Fu',
      sale: 3.29,
      bulk: 1,
      error: false,
      regular: 3.99,
      grocer: 't&t',
      city: 'toronto',
      weight: 1,
      unit: 'L',
      upc: 5,
      vegan: true,
      packaged: true,
      expiry: 1231231212312,
    }, {
      name: 'Royale Facial Tissue',
      brand: 'Royale',
      sale: 7.99,
      bulk: 1,
      error: false,
      regular: 7.99,
      grocer: 't&t',
      city: 'toronto',
      weight: 12,
      unit: 'box',
      upc: 5,
      vegan: true,
      packaged: true,
      expiry: 1231231212312,
    }, {
      name: 'Royale Bathroom Tissue',
      brand: 'Royale',
      sale: 7.77,
      bulk: 1,
      error: false,
      regular: 18.99,
      grocer: 't&t',
      city: 'toronto',
      weight: 24,
      unit: 'roll',
      upc: 5,
      vegan: true,
      packaged: true,
      expiry: 1231231212312,
    }, {
      name: 'Yukon Gold Potatoes',
      brand: '',
      sale: 2.99,
      bulk: 1,
      error: false,
      regular: 5.99,
      grocer: 't&t',
      city: 'toronto',
      weight: 10,
      unit: 'lb',
      upc: 5,
      vegan: true,
      packaged: true,
      expiry: 1231231212312,
    },
  ]